SPAR-48 - SPAR-48-second-language-package
CC2021-WBL/SPAralige-by-Matylda-Borutka pull request #23
Opened 2022-04-09 23:48 UTC by KatarzynaChmielecka

## CR checklist

### a11y
- [ ] test w lighthouse robiony w trybie incognito
- [ ] test a11y  ma wynik powyżej 90% 
- [ ] obrazki mają odpowiednie atrybuty alt
- [ ] obrazki dekoracyjne mają przypisany atrybut aria-hidden=true
- [ ] da się przejść przez aplikację tabem
- [ ] da się potwierdzić wybór elementu enterem
- [ ] linki wyróżnione są nie tylko przez kolor
- [ ] elementy mają przypisaną odpowiednią rolę (atrybut role)
- [ ] nagłówki w odpowiedniej kolejności (tylko jedno h1)
- [ ] strona ma logiczną kolejność tabów
- [ ] element ma odpowiednio oznaczony focus (np. tło, border)
- [ ] teksty są czytelne (mają odpowiedni kontrast)
- [ ] inputy używają autocomplete gdzie to możliwe
- [ ] tekst napisany jest prostym, zrozumiałym językiem (w tym komunikaty dodatkowe, błędy, itd

### inne
- [ ] Build/deploy przechodzi
- [ ] Kod jest zrozumiały
- [ ] Branch działa lokalnie bez błędów
- [ ] PR nie popsuł czyjejś pracy (trzeba przeklikać się przez apkę)
- [ ] Brak błędów w konsoli
- [ ] Nazwa funkcji pokrywa się z nazwą pliku
- [ ] Nazwy zmiennych/obiektów jasno mówią czego dotyczą
- [ ] lintery nie pokazują błędów
- [ ] eslint-disable nie jest na początku pliku (chyba, że jest ważny powód do tego)
- [ ] nie ma zbędnych console.log
- [ ] sprawdź czy za długi kod da się rozdzielić na moduły
- [ ] usunięto zbędne importy i nieużywane zmienne oraz komentarze
- [ ] kolejność komponentu: importy, nazwa komponentu, zmienne, funkcje pomocnicze, hooki, jsx
- [ ] pr z ui zawiera screen oraz opis co zostało zmienione
- [ ] pr ma przypisanego autora
- [ ] pliki są umieszczone w odpowiednich folderach, zgodnie z Atomic Design

2022-04-22 09:50 UTC, vieraboschkova commented on src/i18n.js
> +
Can you try addin here: `lng: 'pl', // default language` ?

2022-04-22 09:51 UTC, vieraboschkova commented on src/i18n.js
> +
If that doesnt work, try other solutions from here: https://stackoverflow.com/questions/65921459/how-to-set-i18n-default-translation-language-in-react

2022-04-22 10:17 UTC, vieraboschkova commented on src/i18n.js
> +
Some more docs about config: https://i18next.github.io/i18next/pages/doc_init.html

2022-04-23 07:20 UTC, MonikaKrella commented
Modal booking is still in polish language at english version
![image](https://user-images.githubusercontent.com/92270179/164884593-0ed13ddf-6682-4990-8d4c-7b1a50a995a6.png)

2022-04-23 07:21 UTC, MonikaKrella commented
Better change to english text, could be by google translator or whatever
![image](https://user-images.githubusercontent.com/92270179/164884655-77a7b7d4-8fea-4717-ac42-1a26ebd80965.png)

2022-04-23 07:22 UTC, MonikaKrella commented
Sign in modal also in polish at english version:
![image](https://user-images.githubusercontent.com/92270179/164884691-e943e942-8e1c-4547-910d-da4f7528fa6d.png)

2022-04-23 07:23 UTC, MonikaKrella commented
same here:
![image](https://user-images.githubusercontent.com/92270179/164884742-d5c04bdd-91ed-47d4-8b6b-f0fcf648ea0c.png)

2022-04-23 07:24 UTC, MonikaKrella commented
and at reservations page:
![image](https://user-images.githubusercontent.com/92270179/164884764-79d055e3-5b7f-4f95-8a6e-971dab5bfa12.png)

2022-04-23 07:25 UTC, MonikaKrella requested changes
added comments to PR what more shoul be included

2022-04-23 08:07 UTC, KatarzynaChmielecka commented
> Better change to english text, could be by google translator or whatever ![image](https://user-images.githubusercontent.com/92270179/164884655-77a7b7d4-8fea-4717-ac42-1a26ebd80965.png)

done

2022-04-23 08:48 UTC, KatarzynaChmielecka commented
> Modal booking is still in polish language at english version ![image](https://user-images.githubusercontent.com/92270179/164884593-0ed13ddf-6682-4990-8d4c-7b1a50a995a6.png)

done ✔️

2022-04-23 10:15 UTC, KatarzynaChmielecka commented
> Sign in modal also in polish at english version, register the same ![image](https://user-images.githubusercontent.com/92270179/164884691-e943e942-8e1c-4547-910d-da4f7528fa6d.png)

Done ✔️

2022-04-23 11:29 UTC, KatarzynaChmielecka commented
> and at reservations page: ![image](https://user-images.githubusercontent.com/92270179/164884764-79d055e3-5b7f-4f95-8a6e-971dab5bfa12.png)

I don't know where is green label data :)) But everything else- done :)

2022-04-23 16:53 UTC, MonikaKrella commented
at contact form:
![image](https://user-images.githubusercontent.com/92270179/164915744-f264aa6f-84b2-483f-9e90-49dced7f0d78.png)
at register:
![image](https://user-images.githubusercontent.com/92270179/164915763-6ec99489-744a-4edf-8f1b-6843d78d193d.png)
All of the previous things are done! :)

2022-04-23 16:59 UTC, MonikaKrella commented
at your branch something crashed app at that moment:
![image](https://user-images.githubusercontent.com/92270179/164915990-f145a906-b6fd-4b4e-8bf9-4359d7045903.png)
it works properly at development.

2022-04-23 17:18 UTC, MonikaKrella commented on src/Components/Atoms/LanguageButton/LanguageButton.tsx
> +// import { makeStyles } from '@mui/styles';
is that commented code necessary? better to remove

2022-04-23 17:20 UTC, MonikaKrella commented on src/Components/Atoms/LanguageButton/LanguageButton.tsx
> +      // className={
same here - is that commented code necessary?

2022-04-23 20:21 UTC, MonikaKrella approved these changes
thats a gigant!

2022-04-23 20:21 UTC, merged

2022-04-23 20:24 UTC, KatarzynaChmielecka commented
> thats a gigant!

it's never ending stooory :D